name: "Create GCP Bucket"
on:
  push:
    branches: gcp-apply-nic-napv5
env:
  TF_VAR_GCP_BUCKET_NAME: ${{ secrets.TF_VAR_GCP_BUCKET_NAME }}
  TF_VAR_GCP_REGION: ${{ secrets.TF_VAR_GCP_REGION }}
  TF_VAR_GCP_PROJECT_ID: ${{ secrets.TF_VAR_GCP_PROJECT_ID }}
  TF_VAR_GOOGLE_CREDENTIALS: ${{ secrets.TF_VAR_GOOGLE_CREDENTIALS }}

jobs:
  terraform_bootstrap:
    name: "Create GCP Bucket"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gcp-test/bucket
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud Credentials
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ secrets.TF_VAR_GOOGLE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out=tfplan

      - name: Check for Changes
        id: check_changes
        run: |
          if grep -q "No changes." <(terraform show -no-color tfplan); then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/gcp-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
        run: terraform apply -auto-approve tfplan

  terraform_infra:
    name: "GCP Infra"
    runs-on: ubuntu-latest
    needs:  terraform_bootstrap
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./gcp-test/infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Google Cloud Credentials
#        uses: google-github-actions/setup-gcloud@v2
#        with:
#          credentials_json: ${{ secrets.TF_VAR_GOOGLE_CREDENTIALS }}

      - name: Authenticate with GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.TF_VAR_GOOGLE_CREDENTIALS }}
        run: |
          echo "${{ secrets.TF_VAR_GOOGLE_CREDENTIALS }}" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS=key.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform (GCS Backend)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.TF_VAR_GOOGLE_CREDENTIALS }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_VAR_GCP_BUCKET_NAME }}"

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        run: |
          terraform plan -no-color -input=false -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Check Changes
        id: check_changes
        run: |
          if grep -q "No changes." plan.txt; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/gcp-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
        run: terraform apply -auto-approve tfplan